version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: knawhuc/lenticular-lens-postgres:latest
    shm_size: 1g
    volumes:
      - ./pgdata:/pgdata
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=postgres

  timbuctoo_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: knawhuc/lenticular-lens-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=timbuctoo

  linkset_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: knawhuc/lenticular-lens-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=linkset

  lens_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: knawhuc/lenticular-lens-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=lens

  clustering_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: knawhuc/lenticular-lens-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=clustering

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    image: knawhuc/lenticular-lens-web:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  gui:
    image: knawhuc/lenticular-lens-gui-vue:latest
    environment:
      - VUE_APP_LENTICULAR_LENS_API=http://127.0.0.1:8000
      - VUE_APP_LENTICULAR_LENS_TITLE=Lenticular Lens
      - VUE_APP_LENTICULAR_LENS_SUB_TITLE=Reconcile data for Golden Agents

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
