version: '3.7'

services:
  postgres:
    build: postgres_timbuctoo
    image: knawhuc/postgres_reconciliation_worker:postgres-latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres_timbuctoo/pgdata:/pgdata
    env_file:
      - .docker-env

  jobs_worker:
    build:
      context: .
      dockerfile: Dockerfile.jobs_worker
    image: knawhuc/postgres_reconciliation_worker:jobs_worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_CONFIG={"host":"postgres","database":"postgres","user":"postgres","password":"postgres"}
      - LC_ALL=de_DE.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
    volumes:
      - output:/output

  timbuctoo_worker:
    build:
      context: .
      dockerfile: Dockerfile.timbuctoo_worker
    image: knawhuc/postgres_reconciliation_worker:timbuctoo_worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_CONFIG={"host":"postgres","database":"postgres","user":"postgres","password":"postgres"}

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    image: knawhuc/postgres_reconciliation_worker:web_server-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_CONFIG={"host":"postgres","database":"postgres","user":"postgres","password":"postgres"}
    ports:
      - 8000:8000
    volumes:
      - output:/output

volumes:
  pgdata:
  common:
  output: