version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: knawhuc/postgres_reconciliation_worker:postgres-latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/pgdata
    environment:
      - PGDATA=/pgdata

  timbuctoo_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=timbuctoo

  alignments_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=alignments

  clusterings_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=clusterings

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    image: knawhuc/postgres_reconciliation_worker:web_server-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8000:8000

  status_monitor:
    build:
      context: .
      dockerfile: Dockerfile.status_monitor
    image: knawhuc/postgres_reconciliation_worker:status_monitor-latest
    depends_on:
      - postgres
      - web_server
      - timbuctoo_worker
      - alignments_worker
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

volumes:
  pgdata:
