version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: knawhuc/postgres_reconciliation_worker:postgres-latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/pgdata
    environment:
      - PGDATA=/pgdata

  timbuctoo_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATA_DIR=/common/src/LLData
      - WORKER_TYPE=timbuctoo
    volumes:
      - output:/common/src/LLData

  alignments_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATA_DIR=/common/src/LLData
      - WORKER_TYPE=alignments
    volumes:
      - output:/common/src/LLData

  clusterings_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/postgres_reconciliation_worker:worker-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATA_DIR=/common/src/LLData
      - WORKER_TYPE=clusterings
    volumes:
      - ./docker/output:/common/src/LLData

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    image: knawhuc/postgres_reconciliation_worker:web_server-latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATA_DIR=/common/src/LLData
    ports:
      - 8000:8000
    volumes:
      - output:/common/src/LLData

  status_monitor:
    build:
      context: .
      dockerfile: Dockerfile.status_monitor
    image: knawhuc/postgres_reconciliation_worker:status_monitor-latest
    depends_on:
      - postgres
      - web_server
      - timbuctoo_worker
      - jobs_worker
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATA_DIR=/common/src/LLData
    volumes:
      - output:/output

volumes:
  pgdata:
  output: