version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: knawhuc/lenticular-lenses-postgres:latest
    shm_size: 1g
    volumes:
      - ./pgdata:/pgdata
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432
