version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: knawhuc/lenticular-lenses-postgres:latest
    shm_size: 1g
    volumes:
      - ./pgdata:/pgdata
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=postgres

  timbuctoo_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/lenticular-lenses-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=timbuctoo

  linkset_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/lenticular-lenses-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=linkset

  clustering_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: knawhuc/lenticular-lenses-worker:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - WORKER_TYPE=clustering

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: knawhuc/lenticular-lenses-web:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8000:8000