name: Example snyk workflow using Python
on:
  push:
 # pull_request:
 #   branches:
 #     - main
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SNyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          
      - name: Continue on Snyk test failure
        run: exit ${{ steps.snyk.outputs.exit_code }} || true
        
          #args: --severity-threshold=high

