name: Example snyk workflow using Python
on:
  push:
 # pull_request:
 #   branches:
 #     - main
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SNyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code monitor
          args: --severity-threshold=high

